разделила отрисовку списка и формы редактирования
htmlacademy-ecmascript/2271085-big-trip-20 pull request #5
Opened 2023-05-13 17:57 UTC by Orixena

2023-05-14 14:56 UTC, rgusseinov requested changes
Привет!

Проверил ДЗ, отлично. В целом все хорошо.
Указал 1 пункт, который надо поправить.

Исправляй и присылай на проверку.

2023-05-14 14:56 UTC, rgusseinov commented on src/view/point-edit-view.js
>    constructor({point = POINT_EMPTY, pointDestination, pointOffers}) {
В BoardPresenter мы передаем обработчики onResetClick: resetButtonClickHandler, и onSubmitClick: pointSubmitHandler, а здесь в компоненте не принимаем их.
Нужно повесить событие submit и reset как указано в задании.
Чтобы карточку можно было закрыть не только через Esc, а через submit и cancel

2023-05-15 06:32 UTC, Orixena commented
спасибо за правки! все исправила)

2023-05-15 09:38 UTC, rgusseinov approved these changes
Привет!

Отлично, исправлено.

2023-05-15 09:38 UTC, merged