добавила заглушку и фильтры
htmlacademy-ecmascript/2271085-big-trip-20 pull request #6
Opened 2023-05-17 06:48 UTC by Orixena

2023-05-17 18:08 UTC, rgusseinov requested changes
Привет!

Проверил и оставил комментарии рядом со строчками.

1. Вижу теперь отрисовывается компонент  в случае если нет точек. Но, при этом не нужно рисовать компонент сортировку. Посмотри пример list-empty.html
2. Еще заметил, в списке точек, offer'ы выводятся через запятую.
Типа так:
Offer taxi +€  51
,
Offer taxi +€  18
Функция createPointOffersTemplate возвращает массив элементов li, а должен возвращать разметку(в виде текста). 
Посмотри в ретро должны были показать как это делается, подсказка через join

Пока все. Как исправишь, отправляй на проверку.
Удачи!)

2023-05-17 18:08 UTC, rgusseinov commented on src/view/filter-view.js
> +  <form class="trip-filers" action="#" method="get">
Перепроверь название класса, что-то не то

2023-05-18 06:06 UTC, Orixena commented on src/view/filter-view.js
> +  <form class="trip-filers" action="#" method="get">
спасибо большое за проверку! исправила ошибки, отправила на проверку)

2023-05-18 08:07 UTC, rgusseinov approved these changes
Привет!

Отлично, молодец!
Теперь исправлено.

2023-05-18 08:07 UTC, merged